export { Layout } from "./layout/Layout";
export { Header } from "./header/Header";
export { Footer } from "./footer/Footer";
export { PhotoSlider } from "./photo-slider/PhotoSlider";
export { CategoryItem } from "./category-item/CategoryItem";
export { ProductItem } from "./product-item/ProductItem";
export { Loader } from "./loader/Loader";
export { ErrorPlaceholder } from "./error-placeholder/ErrorPlaceholder";
export { Benefits } from "./benefts/Benefits";
